import { buildDeckEntry, buildMetaFromSetScope, buildPayload, type DeckEntry } from '@rayenz-hub/shared';
import { downloadSuggestionsJson } from '../lib/hub-utils';
import { buildSwapQueueAnalysis } from './rules';
import type { DeckSuggestState, GenerationRun } from './types';

export function buildExport(state: Pick<DeckSuggestState, 'generationRun' | 'setScope'>) {
  const run = state.generationRun;
  if (!run || !run.deckResults || !run.deckResults.length) {
    throw new Error('No generation results to export.');
  }
  const setScope = state.setScope;
  const decks = run.deckResults.map((result) =>
    buildDeckEntry({
      deck: result.deck as DeckEntry,
      suggestions: (result.suggestions || []) as unknown as DeckEntry['suggestions'],
      analysis: result.analysis ?? undefined,
      skipped: result.skipped || false,
      skip_reason: result.skip_reason || null,
      swapQueueAnalysisFn: buildSwapQueueAnalysis as (deck: DeckEntry) => unknown,
    }),
  );
  return buildPayload(
    buildMetaFromSetScope(setScope as Parameters<typeof buildMetaFromSetScope>[0], 'Generated by Deck Suggest (rule-based); no LLM.'),
    decks,
  );
}

export function downloadJson(state: Pick<DeckSuggestState, 'generationRun' | 'setScope'>): string {
  const payload = buildExport(state);
  return downloadSuggestionsJson(payload);
}

export function buildSummary(st: Pick<DeckSuggestState, 'generationRun' | 'setScope'>) {
  const run = st.generationRun;
  if (!run || !run.deckResults) {
    return null;
  }
  let totalSwap = 0;
  let totalNormal = 0;
  let skippedQueue = 0;
  const deckRows: Array<{
    deck_id: string;
    deck_name: string;
    swap: number;
    normal: number;
    total: number;
    skipped: boolean;
    error: string | null;
    message: string | null;
  }> = [];
  (run.deckResults || []).forEach((result) => {
    const list = result.suggestions || [];
    let swap = 0;
    let normal = 0;
    list.forEach((s) => {
      if (s.priority_tier === 'swap') {
        swap += 1;
      } else {
        normal += 1;
      }
    });
    totalSwap += swap;
    totalNormal += normal;
    deckRows.push({
      deck_id: result.deck.deck_id,
      deck_name: result.deck.deck_name,
      swap,
      normal,
      total: list.length,
      skipped: !!result.skipped,
      error: result.error || null,
      message: result.message || null,
    });
  });
  (run.rulesExecuted || []).forEach((a) => {
    if (a.skippedReason && String(a.skippedReason).indexOf('not_in_set_scope') >= 0) {
      skippedQueue += 1;
    }
  });
  const setScope = st.setScope || { codes: [], cards: [] };
  return {
    totalSuggestions: totalSwap + totalNormal,
    totalSwap,
    totalNormal,
    deckRows,
    skippedQueueSlots: skippedQueue,
    setCodes: setScope.codes || [],
    poolSize: (setScope.cards || []).length,
  };
}

export function hasReviewableSuggestions(st: Pick<DeckSuggestState, 'generationRun' | 'setScope'>): boolean {
  if (!st.generationRun) {
    return false;
  }
  try {
    const payload = buildExport(st);
    return (payload.decks || []).some((d) => (d.suggestions || []).length > 0);
  } catch {
    return false;
  }
}

export const Export = {
  buildExport,
  buildSummary,
  hasReviewableSuggestions,
  downloadJson,
};

export type ExportSummary = NonNullable<ReturnType<typeof buildSummary>>;

export function collectDebugEntries(
  run: GenerationRun,
  filterText?: string,
): Array<{ deckId: string; deckName: string; entry: import('./types').DebugEntry }> {
  const entries: Array<{ deckId: string; deckName: string; entry: import('./types').DebugEntry }> = [];
  (run.deckResults || []).forEach((result) => {
    const trace = result.debugTrace || [];
    trace.forEach((entry) => {
      entries.push({
        deckId: result.deck.deck_id,
        deckName: result.deck.deck_name,
        entry,
      });
    });
  });
  if (!filterText) {
    return entries;
  }
  const needle = String(filterText).trim().toLowerCase();
  if (!needle) {
    return entries;
  }
  return entries.filter((row) => {
    const e = row.entry;
    return [e.subject, e.cardIn, e.cardOut].some(
      (field) => field && String(field).toLowerCase().indexOf(needle) >= 0,
    );
  });
}
