(function (global) {
   'use strict';

   var DS = global.DeckSuggest;

   function buildExport(state) {
      var run = state.generationRun;
      if (!run || !run.deckResults || !run.deckResults.length) {
         throw new Error('No generation results to export.');
      }
      var setScope = state.setScope;
      var decks = run.deckResults.map(function (result) {
         return SuggestionsBundle.buildDeckEntry({
            deck: result.deck,
            suggestions: result.suggestions || [],
            analysis: result.analysis,
            skipped: result.skipped || false,
            skip_reason: result.skip_reason || null,
            swapQueueAnalysisFn: DS.buildSwapQueueAnalysis
         });
      });
      return SuggestionsBundle.buildPayload(
         SuggestionsBundle.buildMetaFromSetScope(
            setScope,
            'Generated by Deck Suggest (rule-based); no LLM.'
         ),
         decks
      );
   }

   function downloadJson(state) {
      var payload = buildExport(state);
      return HubUtils.downloadSuggestionsJson(payload);
   }

   function buildSummary(st) {
      var run = st.generationRun;
      if (!run || !run.deckResults) {
         return null;
      }
      var totalSwap = 0;
      var totalNormal = 0;
      var skippedQueue = 0;
      var deckRows = [];
      (run.deckResults || []).forEach(function (result) {
         var list = result.suggestions || [];
         var swap = 0;
         var normal = 0;
         list.forEach(function (s) {
            if (s.priority_tier === 'swap') {
               swap += 1;
            } else {
               normal += 1;
            }
         });
         totalSwap += swap;
         totalNormal += normal;
         deckRows.push({
            deck_id: result.deck.deck_id,
            deck_name: result.deck.deck_name,
            swap: swap,
            normal: normal,
            total: list.length,
            skipped: !!result.skipped,
            error: result.error || null,
            message: result.message || null
         });
      });
      (run.rulesExecuted || []).forEach(function (a) {
         if (a.skippedReason && String(a.skippedReason).indexOf('not_in_set_scope') >= 0) {
            skippedQueue += 1;
         }
      });
      var setScope = st.setScope || {};
      return {
         totalSuggestions: totalSwap + totalNormal,
         totalSwap: totalSwap,
         totalNormal: totalNormal,
         deckRows: deckRows,
         skippedQueueSlots: skippedQueue,
         setCodes: setScope.codes || [],
         poolSize: (setScope.cards || []).length
      };
   }

   function hasReviewableSuggestions(st) {
      if (!st.generationRun) {
         return false;
      }
      try {
         var payload = buildExport(st);
         return (payload.decks || []).some(function (d) {
            return (d.suggestions || []).length > 0;
         });
      } catch (e) {
         return false;
      }
   }

   DS.Export = {
      buildExport: buildExport,
      buildSummary: buildSummary,
      hasReviewableSuggestions: hasReviewableSuggestions,
      downloadJson: downloadJson
   };
})(window);
